// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5RIFqfAsLWzgncVTfzxOhxXIy606PaDI',
    appId: '1:527635349737:web:5ccc19516a9d5168f0f078',
    messagingSenderId: '527635349737',
    projectId: 'grocery-list-and-expiry-track',
    authDomain: 'grocery-list-and-expiry-track.firebaseapp.com',
    storageBucket: 'grocery-list-and-expiry-track.firebasestorage.app',
    measurementId: 'G-WTQ82YXXEK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq-a82iR6yU_dncP-X3iBZkakGxa9Ms5k',
    appId: '1:527635349737:android:09a4273c5a8fdc33f0f078',
    messagingSenderId: '527635349737',
    projectId: 'grocery-list-and-expiry-track',
    storageBucket: 'grocery-list-and-expiry-track.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFj3c13uqwFN_nunrCmVhUOucJGgdpiSU',
    appId: '1:527635349737:ios:dbb9bc5636e5de9ff0f078',
    messagingSenderId: '527635349737',
    projectId: 'grocery-list-and-expiry-track',
    storageBucket: 'grocery-list-and-expiry-track.firebasestorage.app',
    iosBundleId: 'com.school.grocerytracker.groceryTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFj3c13uqwFN_nunrCmVhUOucJGgdpiSU',
    appId: '1:527635349737:ios:dbb9bc5636e5de9ff0f078',
    messagingSenderId: '527635349737',
    projectId: 'grocery-list-and-expiry-track',
    storageBucket: 'grocery-list-and-expiry-track.firebasestorage.app',
    iosBundleId: 'com.school.grocerytracker.groceryTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5RIFqfAsLWzgncVTfzxOhxXIy606PaDI',
    appId: '1:527635349737:web:abe71c1a0d9f5ce5f0f078',
    messagingSenderId: '527635349737',
    projectId: 'grocery-list-and-expiry-track',
    authDomain: 'grocery-list-and-expiry-track.firebaseapp.com',
    storageBucket: 'grocery-list-and-expiry-track.firebasestorage.app',
    measurementId: 'G-0ZQJ1F3GRF',
  );
}
